/* Assembles the paste-ready block for the Rajadamnern Knockout hub.
 *
 *   node gen.mjs && node build.mjs
 *
 * Writes to files, not to stdout.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const head = `<!--
  RAJADAMNERN KNOCKOUT, EVERGREEN HUB  (page address: /rajadamnern-knockout)
  Paste this whole thing into one HTML block (Tilda T123) on the page.

  Meta title, meta description, Open Graph and canonical are NOT in here.
  Tilda owns those; the text is in TILDA-PAGE-SETTINGS.txt.

  Every visible word is read from copy.json by gen.mjs. Do not edit this file
  by hand: change copy.json and rebuild.

  The booking widget mounts into the element marked data-mtx-slot. It needs the
  MuayTix header block already pasted into Tilda Site Settings, More, HTML code
  for the HEAD.

  Placeholders still to fill: the dome picture (data-placeholder="dome-image")
  and the second link in the event chooser (data-needs-destination).
-->
<div class="mtx-kh-page" id="mtx-kh">
<style>
`;

const schema = JSON.parse(readFileSync('schema.json', 'utf8'));
if (!Array.isArray(schema) || schema.length !== 2) { console.error('schema.json should hold two objects'); process.exit(1); }
const parts = [head, readFileSync('style.css', 'utf8'), '</style>\n\n', readFileSync('body.html', 'utf8'), readFileSync('tail.html', 'utf8')];
const source = parts.join('')
  .replace('@@SCHEMA_1@@', JSON.stringify(schema[0], null, 2))
  .replace('@@SCHEMA_2@@', JSON.stringify(schema[1], null, 2));
if (/@@[A-Z_0-9]+@@/.test(source)) { console.error('A build token was left unfilled'); process.exit(1); }
writeFileSync('knockout-hub-source.html', source);

const live = source
  .replace(/<style>([\s\S]*?)<\/style>/g, (_, css) =>
    '<style>' + css.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\n{3,}/g, '\n\n').trim() + '</style>')
  .replace(/<!--[\s\S]*?-->/g, '')
  .replace(/\n{3,}/g, '\n\n')
  .trim() + '\n';

writeFileSync('knockout-hub-live.txt', live);
writeFileSync('rajadamnern-knockout-hub-PASTE-INTO-TILDA.html', live);
console.log('source', (source.length / 1024).toFixed(1) + ' KB');
console.log('live  ', (live.length / 1024).toFixed(1) + ' KB  (written to 2 files)');
