/* Assembles the paste-ready block for the rolling Rajadamnern Knockout
 * fight-card page.
 *
 *   node gen.mjs && node build.mjs
 *
 * Writes to files, not to stdout. OUT_DIR is for the checker only.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const OUT = process.env.OUT_DIR || '.';
const head = `<!--
  RAJADAMNERN KNOCKOUT SCHEDULE  (page address: /rajadamnern-knockout/schedule)
  Paste this whole thing into one HTML block (Tilda T123) on the page.

  Meta title, meta description, Open Graph and canonical are NOT in here.
  Tilda owns those; the text is in TILDA-PAGE-SETTINGS.txt.

  Every visible word is read from copy.json by gen.mjs. Do not edit this file
  by hand: change copy.json or data.json
  and rebuild.
-->
<div class="mtx-ks-page" id="mtx-ks">
<style>
`;

const schema = JSON.parse(readFileSync(`${OUT}/schema.json`, 'utf8'));
const tags = schema.map(s => `<script type="application/ld+json">\n${JSON.stringify(s, null, 2)}\n</script>`).join('\n\n');
const source = [head, readFileSync('style.css', 'utf8'), '</style>\n\n', readFileSync(`${OUT}/body.html`, 'utf8'), readFileSync('tail.html', 'utf8')]
  .join('').replace('@@SCHEMA@@', tags);
if (/@@[A-Z_0-9]+@@/.test(source)) { console.error('A build token was left unfilled'); process.exit(1); }
writeFileSync(`${OUT}/schedule-source.html`, source);

const live = source
  .replace(/<style>([\s\S]*?)<\/style>/g, (_, css) =>
    '<style>' + css.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\n{3,}/g, '\n\n').trim() + '</style>')
  .replace(/<!--[\s\S]*?-->/g, '')
  .replace(/\n{3,}/g, '\n\n')
  .trim() + '\n';

writeFileSync(`${OUT}/schedule-live.txt`, live);
if (!process.env.OUT_DIR) writeFileSync('rajadamnern-knockout-schedule-PASTE-INTO-TILDA.html', live);
console.log('source', (source.length / 1024).toFixed(1) + ' KB');
console.log('live  ', (live.length / 1024).toFixed(1) + ' KB');
