/* Assembles the paste-ready block for RWS Knocktoberfest, 10 October 2026.
 *
 *   node gen.mjs && node build.mjs
 *
 * Writes to files, not to stdout.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const head = `<!--
  RWS KNOCKTOBERFEST, SATURDAY 10 OCTOBER 2026
  Paste this whole thing into one HTML block (Tilda T123) on the page.

  Meta title, meta description, Open Graph and canonical are NOT in here.
  Tilda owns those; the text is in TILDA-PAGE-SETTINGS.txt.

  Every visible word is read from copy.json by gen.mjs. Do not edit this file
  by hand: change copy.json and rebuild.

  The booking widget mounts into the element marked data-mtx-slot. It needs the
  MuayTix header block already pasted into Tilda Site Settings, More, HTML code
  for the HEAD.
-->
<div class="mtx-kt-page" id="mtx-kt">
<style>
`;

const parts = [head, readFileSync('style.css', 'utf8'), '</style>\n\n', readFileSync('body.html', 'utf8'), readFileSync('tail.html', 'utf8')];
const source = parts.join('').replace('@@SCHEMA@@', readFileSync('schema.json', 'utf8').trim());
if (/@@[A-Z_]+@@/.test(source)) { console.error('A build token was left unfilled'); process.exit(1); }
writeFileSync('knocktober-source.html', source);

const live = source
  .replace(/<style>([\s\S]*?)<\/style>/g, (_, css) =>
    '<style>' + css.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\n{3,}/g, '\n\n').trim() + '</style>')
  .replace(/<!--[\s\S]*?-->/g, '')
  .replace(/\n{3,}/g, '\n\n')
  .trim() + '\n';

writeFileSync('knocktober-live.txt', live);
writeFileSync('rws-knocktoberfest-10-OCT-PASTE-INTO-TILDA.html', live);
console.log('source', (source.length / 1024).toFixed(1) + ' KB');
console.log('live  ', (live.length / 1024).toFixed(1) + ' KB  (written to 2 files)');
